let food = [
    
    {
    "name": "tomato",
    "calories": 18,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 0.9,
    "sodium_mg": 5,
    "potassium_mg": 237,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.9,
    "fiber_g": 1.2,
    "sugar_g": 2.6
    },
    {
    "name": "carrot",
    "calories": 41,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 0.9,
    "sodium_mg": 69,
    "potassium_mg": 320,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 9.6,
    "fiber_g": 2.8,
    "sugar_g": 4.7
    },
    {
    "name": "broccoli",
    "calories": 34,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0.1,
    "protein_g": 2.8,
    "sodium_mg": 33,
    "potassium_mg": 316,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.6,
    "fiber_g": 2.6,
    "sugar_g": 1.7
    },
    {
    "name": "spinach",
    "calories": 23,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0.1,
    "protein_g": 2.9,
    "sodium_mg": 79,
    "potassium_mg": 558,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.6,
    "fiber_g": 2.2,
    "sugar_g": 0.4
    },
    {
    "name": "potato",
    "calories": 77,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 2,
    "sodium_mg": 6,
    "potassium_mg": 425,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 17.6,
    "fiber_g": 2.2,
    "sugar_g": 0.8
    },
    {
    "name": "artichoke",
    "calories": 47,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 3.3,
    "sodium_mg": 94,
    "potassium_mg": 370,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 10.5,
    "fiber_g": 5.4,
    "sugar_g": 1.2
    },
    {
    "name": "asparagus",
    "calories": 20,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 2.2,
    "sodium_mg": 2,
    "potassium_mg": 202,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.9,
    "fiber_g": 2.1,
    "sugar_g": 1.9
    },
    {
    "name": "eggplant",
    "calories": 25,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1,
    "sodium_mg": 2,
    "potassium_mg": 229,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 5.9,
    "fiber_g": 3,
    "sugar_g": 3.5
    },
    {
    "name": "avocado",
    "calories": 160,
    "serving_size_g": 100,
    "fat_total_g": 14.7,
    "fat_saturated_g": 2.1,
    "protein_g": 2,
    "sodium_mg": 7,
    "potassium_mg": 485,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 8.5,
    "fiber_g": 6.7,
    "sugar_g": 0.7
    },
    {
    "name": "beet",
    "calories": 43,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.6,
    "sodium_mg": 78,
    "potassium_mg": 325,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 9.6,
    "fiber_g": 2.8,
    "sugar_g": 6.8
    },
    {
    "name": "bok choy",
    "calories": 13,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.5,
    "sodium_mg": 65,
    "potassium_mg": 252,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 2.2,
    "fiber_g": 1,
    "sugar_g": 1.2
    },
    {
    "name": "broccoli",
    "calories": 34,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0.1,
    "protein_g": 2.8,
    "sodium_mg": 33,
    "potassium_mg": 316,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.6,
    "fiber_g": 2.6,
    "sugar_g": 1.7
    },
    {
    "name": "broccolini",
    "calories": 35,
    "serving_size_g": 100,
    "fat_total_g": 0.5,
    "fat_saturated_g": 0,
    "protein_g": 2.4,
    "sodium_mg": 30,
    "potassium_mg": 325,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.3,
    "fiber_g": 3.7,
    "sugar_g": 1.1
    },
    {
    "name": "broccoli raab",
    "calories": 22,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 3.3,
    "sodium_mg": 33,
    "potassium_mg": 196,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 2.9,
    "fiber_g": 2.7,
    "sugar_g": 0.4
    },
    {
    "name": "brussels sprouts",
    "calories": 43,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0.1,
    "protein_g": 3.4,
    "sodium_mg": 25,
    "potassium_mg": 389,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 8.9,
    "fiber_g": 3.8,
    "sugar_g": 2.2
    },
    {
    "name": "chinese cabbage",
    "calories": 12,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.2,
    "sodium_mg": 53,
    "potassium_mg": 170,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 2.2,
    "fiber_g": 1.4,
    "sugar_g": 1.3
    },
    {
    "name": "green cabbage",
    "calories": 25,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.3,
    "sodium_mg": 18,
    "potassium_mg": 170,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 5.8,
    "fiber_g": 2.5,
    "sugar_g": 3.2
    },
    {
    "name": "purple cabbage",
    "calories": 31,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.4,
    "sodium_mg": 20,
    "potassium_mg": 213,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 7.4,
    "fiber_g": 2.1,
    "sugar_g": 3.2
    },
    {
    "name": "savoy cabbage",
    "calories": 27,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.7,
    "sodium_mg": 25,
    "potassium_mg": 180,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.2,
    "fiber_g": 2.6,
    "sugar_g": 3.2
    },
    {
    "name": "cauliflower",
    "calories": 25,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 1.9,
    "sodium_mg": 30,
    "potassium_mg": 142,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.9,
    "fiber_g": 2,
    "sugar_g": 1.9
    },
    {
    "name": "celeriac",
    "calories": 42,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 1.5,
    "sodium_mg": 56,
    "potassium_mg": 300,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 9.2,
    "fiber_g": 1.8,
    "sugar_g": 1.2
    },
    {
    "name": "celery",
    "calories": 16,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 0.7,
    "sodium_mg": 80,
    "potassium_mg": 260,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.5,
    "fiber_g": 1.6,
    "sugar_g": 1.4
    },
    {
    "name": "chard",
    "calories": 19,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.8,
    "sodium_mg": 213,
    "potassium_mg": 379,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.7,
    "fiber_g": 1.6,
    "sugar_g": 1.1
    },
    {
    "name": "chicory",
    "calories": 23,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.2,
    "sodium_mg": 22,
    "potassium_mg": 230,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.7,
    "fiber_g": 3.1,
    "sugar_g": 0.6
    },
    {
    "name": "corn",
    "calories": 96,
    "serving_size_g": 100,
    "fat_total_g": 1.5,
    "fat_saturated_g": 0.2,
    "protein_g": 3.4,
    "sodium_mg": 15,
    "potassium_mg": 270,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 19,
    "fiber_g": 2.7,
    "sugar_g": 6.3
    },
    {
    "name": "cress",
    "calories": 11,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.3,
    "sodium_mg": 41,
    "potassium_mg": 330,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 1.3,
    "fiber_g": 0.8,
    "sugar_g": 0.3
    },
    {
    "name": "cucumbers",
    "calories": 16,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 0.7,
    "sodium_mg": 2,
    "potassium_mg": 147,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.6,
    "fiber_g": 0.5,
    "sugar_g": 1.7
    },
    {
    "name": "daikon",
    "calories": 18,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1,
    "sodium_mg": 16,
    "potassium_mg": 233,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.1,
    "fiber_g": 1.6,
    "sugar_g": 1.9
    },
    {
    "name": "garlic",
    "calories": 149,
    "serving_size_g": 100,
    "fat_total_g": 0.5,
    "fat_saturated_g": 0.1,
    "protein_g": 6.4,
    "sodium_mg": 17,
    "potassium_mg": 401,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 33.1,
    "fiber_g": 2.1,
    "sugar_g": 1
    },
    {
    "name": "green beans",
    "calories": 31,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.8,
    "sodium_mg": 6,
    "potassium_mg": 211,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 7,
    "fiber_g": 3.4,
    "sugar_g": 3.6
    },
    {
    "name": "greens",
    "calories": 23,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0,
    "protein_g": 2.2,
    "sodium_mg": 23,
    "potassium_mg": 330,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.1,
    "fiber_g": 2.5,
    "sugar_g": 1.2
    },
    {
    "name": "collard greens",
    "calories": 32,
    "serving_size_g": 100,
    "fat_total_g": 0.6,
    "fat_saturated_g": 0.1,
    "protein_g": 3.0,
    "sodium_mg": 20,
    "potassium_mg": 213,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.7,
    "fiber_g": 4.0,
    "sugar_g": 0.5
    },
    {
    "name": "mustard greens",
    "calories": 27,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 2.7,
    "sodium_mg": 13,
    "potassium_mg": 247,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 5.4,
    "fiber_g": 3.2,
    "sugar_g": 1.3
    },
    {
    "name": "gourds",
    "calories": 19,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.0,
    "sodium_mg": 16,
    "potassium_mg": 200,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.9,
    "fiber_g": 1.8,
    "sugar_g": 3.0
    },
    {
    "name": "kale",
    "calories": 49,
    "serving_size_g": 100,
    "fat_total_g": 0.9,
    "fat_saturated_g": 0.1,
    "protein_g": 4.3,
    "sodium_mg": 38,
    "potassium_mg": 491,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 9,
    "fiber_g": 4.1,
    "sugar_g": 0.7
    },
    {
    "name": "leeks",
    "calories": 61,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 1.5,
    "sodium_mg": 20,
    "potassium_mg": 180,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 14.2,
    "fiber_g": 1.6,
    "sugar_g": 3.9
    },
    {
    "name": "arugula",
    "calories": 25,
    "serving_size_g": 100,
    "fat_total_g": 0.7,
    "fat_saturated_g": 0.1,
    "protein_g": 2.6,
    "sodium_mg": 27,
    "potassium_mg": 369,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.7,
    "fiber_g": 1.6,
    "sugar_g": 2.1
    },
    {
    "name": "lettuce",
    "calories": 15,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.4,
    "sodium_mg": 28,
    "potassium_mg": 194,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3,
    "fiber_g": 1.2,
    "sugar_g": 0.7
    },
    {
    "name": "mushrooms",
    "calories": 22,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0.1,
    "protein_g": 3.1,
    "sodium_mg": 5,
    "potassium_mg": 318,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.3,
    "fiber_g": 1.0,
    "sugar_g": 2.0
    },
    {
    "name": "okra",
    "calories": 33,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0.1,
    "protein_g": 1.9,
    "sodium_mg": 7,
    "potassium_mg": 299,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 7.5,
    "fiber_g": 3.2,
    "sugar_g": 1.5
    },
    {
    "name": "onions",
    "calories": 40,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.1,
    "sodium_mg": 4,
    "potassium_mg": 146,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 9.3,
    "fiber_g": 1.7,
    "sugar_g": 4.2
    },
    {
    "name": "green onions",
    "calories": 32,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.8,
    "sodium_mg": 16,
    "potassium_mg": 276,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 7.3,
    "fiber_g": 2.6,
    "sugar_g": 2.3
    },
    {
    "name": "peas",
    "calories": 81,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0.1,
    "protein_g": 5.4,
    "sodium_mg": 5,
    "potassium_mg": 244,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 14.5,
    "fiber_g": 5.7,
    "sugar_g": 4.3
    },
    {
    "name": "snap sugar peas",
    "calories": 42,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 2.8,
    "sodium_mg": 5,
    "potassium_mg": 190,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 7.6,
    "fiber_g": 2.6,
    "sugar_g": 3.5
    },
    {
    "name": "snow peas",
    "calories": 42,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 2.8,
    "sodium_mg": 6,
    "potassium_mg": 209,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 7.6,
    "fiber_g": 2.6,
    "sugar_g": 3.3
    },
    {
    "name": "potatoes",
    "calories": 77,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 2.0,
    "sodium_mg": 7,
    "potassium_mg": 429,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 17.5,
    "fiber_g": 2.2,
    "sugar_g": 0.8
    },
    {
    "name": "pumpkin",
    "calories": 26,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.0,
    "sodium_mg": 1,
    "potassium_mg": 340,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.5,
    "fiber_g": 0.5,
    "sugar_g": 2.8
    },
    {
    "name": "radicchio",
    "calories": 23,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0.1,
    "protein_g": 1.6,
    "sodium_mg": 6,
    "potassium_mg": 303,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.4,
    "fiber_g": 2.1,
    "sugar_g": 2.0
    },
    {
    "name": "radish",
    "calories": 16,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 0.7,
    "sodium_mg": 39,
    "potassium_mg": 233,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.4,
    "fiber_g": 1.6,
    "sugar_g": 1.9
    },
    {
    "name": "rhubarb",
    "calories": 21,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 0.9,
    "sodium_mg": 3,
    "potassium_mg": 288,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 4.5,
    "fiber_g": 1.8,
    "sugar_g": 1.1
    },
    
    {
    "name": "romanesco",
    "calories": 30,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 2.4,
    "sodium_mg": 30,
    "potassium_mg": 350,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.7,
    "fiber_g": 3.2,
    "sugar_g": 1.9
    },
    {
    "name": "rutabaga",
    "calories": 38,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.1,
    "sodium_mg": 20,
    "potassium_mg": 305,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 8.6,
    "fiber_g": 2.3,
    "sugar_g": 3.6
    },
    {
    "name": "shallots",
    "calories": 72,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 2.5,
    "sodium_mg": 6,
    "potassium_mg": 334,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 16.8,
    "fiber_g": 3.2,
    "sugar_g": 7.9
    },
    {
    "name": "spinach",
    "calories": 23,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0.1,
    "protein_g": 2.9,
    "sodium_mg": 79,
    "potassium_mg": 558,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.6,
    "fiber_g": 2.2,
    "sugar_g": 0.4
    },
    {
    "name": "squash",
    "calories": 45,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.0,
    "sodium_mg": 1,
    "potassium_mg": 260,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 11.0,
    "fiber_g": 1.5,
    "sugar_g": 4.0
    },
    {
    "name": "butternut squash",
    "calories": 45,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.0,
    "sodium_mg": 2,
    "potassium_mg": 350,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 11.0,
    "fiber_g": 2.0,
    "sugar_g": 4.0
    },
    {
    "name": "sweet potato",
    "calories": 86,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.6,
    "sodium_mg": 55,
    "potassium_mg": 337,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 20.1,
    "fiber_g": 3.0,
    "sugar_g": 4.2
    },
    {
    "name": "tomatoes",
    "calories": 18,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 0.9,
    "sodium_mg": 5,
    "potassium_mg": 237,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.9,
    "fiber_g": 1.2,
    "sugar_g": 2.6
    },
{
    "name": "turnips",
    "calories": 28,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 0.9,
    "sodium_mg": 20,
    "potassium_mg": 233,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 6.4,
    "fiber_g": 1.8,
    "sugar_g": 3.8
    },
    {
    "name": "water chestnuts",
    "calories": 97,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 3.0,
    "sodium_mg": 5,
    "potassium_mg": 370,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 23.9,
    "fiber_g": 3.1,
    "sugar_g": 7.0
    },
    {
    "name": "yam",
    "calories": 118,
    "serving_size_g": 100,
    "fat_total_g": 0.2,
    "fat_saturated_g": 0,
    "protein_g": 1.5,
    "sodium_mg": 55,
    "potassium_mg": 437,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 27.9,
    "fiber_g": 4.1,
    "sugar_g": 4.2
    },
    {
    "name": "zucchini",
    "calories": 17,
    "serving_size_g": 100,
    "fat_total_g": 0.3,
    "fat_saturated_g": 0,
    "protein_g": 1.2,
    "sodium_mg": 8,
    "potassium_mg": 261,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.1,
    "fiber_g": 1.0,
    "sugar_g": 2.5
    },
    {
    "name": "bottle gourd",
    "calories": 14,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 1.0,
    "sodium_mg": 2,
    "potassium_mg": 147,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.2,
    "fiber_g": 0.5,
    "sugar_g": 2.0
    },
    {
    "name": "white radish",
    "calories": 16,
    "serving_size_g": 100,
    "fat_total_g": 0.1,
    "fat_saturated_g": 0,
    "protein_g": 0.9,
    "sodium_mg": 39,
    "potassium_mg": 233,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.4,
    "fiber_g": 1.6,
    "sugar_g": 1.9
    },
    {
    "name": "bitter gourd",
    "calories": 17,
    "serving_size_g": 100,
    "fat_total_g": 0.4,
    "fat_saturated_g": 0.1,
    "protein_g": 1.0,
    "sodium_mg": 4,
    "potassium_mg": 319,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 3.4,
    "fiber_g": 2.8,
    "sugar_g": 2.4
    },
    {
    "name": "fenugreek leaves",
    "calories": 49,
    "serving_size_g": 100,
    "fat_total_g": 0.9,
    "fat_saturated_g": 0.1,
    "protein_g": 4.0,
    "sodium_mg": 67,
    "potassium_mg": 195,
    "cholesterol_mg": 0,
    "carbohydrates_total_g": 8.7,
    "fiber_g": 6.0,
    "sugar_g": 0.9
    }
]




module.exports = food;